### ISSUE TITLE
Enable abstraction and @-expression?

### ISSUE THREAD

**Issue by sorawee** [racket/string-constants#37]
Would it be a good idea to enable @-expression and allow some definitions?

```
(define file <translation-of-file>)

(translation
  ...
  [cs-open-defining-file @~a{..... @file}]
  ...)
```

I'm translating to Thai language and find myself translating some words inconsistently. This feature would reduce the error.

**Comment by rfindler** [comment]
I'm not sure that @-expressions are a good idea. They have pretty complex rules that are definitely worth learning for other contexts, but perhaps it is too much to ask for translators (especially since we can't really give good error messages in cases that people make simple mistakes).

I just pushed a change that adds `#:define`, tho, so maybe that'll be good enough? 

If not, the string-constants library really just needs to provide a hash mapping names to strings, so it may make sense to have a lang that you use for the Thai translation?

**Comment by sorawee** [comment]
Can you remove the restriction that middle strings must have spaces at the beginning? Some non-English languages (including Thai, and I think Chinese as well) don't have whitespaces between words.

But besides that, everything is perfect. Thank you very much :)

**Comment by sorawee** [comment]
Oh, I thought this restriction was added by your recent commits. Just found out that it's been there for a while. 

But yeah, this restriction makes the "multi-line" (should really call it "multi-term") feature less useful in languages that don't have word boundary (Thai, Chinese, Japanese, Korean, etc.).

Perhaps, if we really don't want to give up this restriction, there should be a flag whether or not this restriction should be enforced?

**Comment by rfindler** [comment]
Yeah I agree that a flag makes sense; this restriction is very useful for
me in English!

**Comment by sorawee** [comment]
Thanks!

**Comment by rfindler** [comment]
I'm delighted you're considering translating DrRacket to Thai!
